PROGNAME=yabh
VERBOSITY_LEVEL=0

# Return values
RETURN_SUCCESS=0
RETURN_COMMANDLINE_ERROR=1
RETURN_CONFIGURATION_ERROR=2
RETURN_NOT_ROOT_ERROR=3
RETURN_ENVIRONMENT_ERROR=4
RETURN_JAIL_ERROR=5

HYPERVISOR_RELEASE_BASE_URL="https://download.freebsd.org/ftp/releases/amd64"
JAIL_DEFAULT_DEVFSRULESET=5
